### ISSUE TITLE
Google Storage Account is no longer active

### ISSUE THREAD

**Issue by Ryan0751** [shackrat/SmartThings-by-Shackrat#4]
The Google Storage account referenced by the code for obtaining App icons as well as the latest version has been closed:

<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 1070783070122 is disabled in state closed
</Details>
</Error>

This is preventing the App from functioning properly as it's written today.

**Comment by storyd** [comment]
There is a work around, go find a icon you want to use (or make one) and host it somewhere publicly available (S3, imgur).

1. Go through the SmartApp src and find and replace the googleapi references to your new image.
2. Go all the way to the bottom and replace the entire contents of the getLatestVersion function and replace with `"1".toDouble()`
3. Publish (to me) the changes.

The larger question is why weren't the images put in the repo and hosted from github directly?
